services:
  # Gateway service
  gateway:
    image: node:lts
    container_name: example-gateway
    restart: unless-stopped
    command: npm run start:dev
    working_dir: /app
    networks:
      - example-network
    ports:
      - 3000:3000
    environment:
      - GATEWAY_SERVICE_PORT=3000
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./gateway-service:/app

  # Auth service
  auth:
    image: node:lts
    container_name: example-auth
    restart: unless-stopped
    command: "npm run start:dev"
    working_dir: /app
    networks:
      - example-network
    ports:
      - 3001:3000
    environment:
      - AUTH_SERVICE_PORT=3000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./auth-service:/app
      - ./shared:/app/shared
      - /app/node_modules

  # User service
  user:
    image: node:lts
    container_name: example-user
    restart: unless-stopped
    command: "npm run start:dev"
    working_dir: /app
    networks:
      - example-network
    ports:
      - 3002:3000
    environment:
      - USER_SERVICE_PORT=3000
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./user-service:/app
      - ./shared:/app/shared
      - /app/node_modules

networks:
  example-network:
    driver: bridge

volumes:
  db-volume: # Persist data for the database
